### ISSUE TITLE
how to set dojoConfig before the webpack

### ISSUE THREAD

**Issue by giserMao** [odoe/jsapi-webpack#4]

**Comment by giserMao** [comment]
hi odoe:
         When I want to set the locale of arcgis to "zh-cn", the dojoconfig configuration does not work.
I guess the reason is that djconfig is loaded after webpack.

**Comment by odoe** [comment]
You can set the locales as part of the [arcgis-webpack-plugin options](https://github.com/esri/arcgis-webpack-plugin#options).

This will create a smaller deployed output as only the files for the specified locales will be included.
